/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CommunityWalletRouteImport } from './routes/community-wallet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NgoVerificationRouteImport } from './routes/ngo.verification'
import { Route as NgoProfileRouteImport } from './routes/ngo.profile'
import { Route as NgoNotVerifiedRouteImport } from './routes/ngo.not-verified'
import { Route as NgoExploreRouteImport } from './routes/ngo.explore'
import { Route as NgoDashboardRouteImport } from './routes/ngo.dashboard'
import { Route as NgoClaimsRouteImport } from './routes/ngo.claims'
import { Route as DonorProfileRouteImport } from './routes/donor.profile'
import { Route as DonorNetworkRouteImport } from './routes/donor.network'
import { Route as DonorImpactRouteImport } from './routes/donor.impact'
import { Route as DonorHistoryRouteImport } from './routes/donor.history'
import { Route as DonorDashboardRouteImport } from './routes/donor.dashboard'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as NgoTrackIdRouteImport } from './routes/ngo.track.$id'
import { Route as NgoDonationsIdRouteImport } from './routes/ngo.donations.$id'
import { Route as DonorDonateSuccessRouteImport } from './routes/donor.donate.success'
import { Route as DonorDonateReviewRouteImport } from './routes/donor.donate.review'
import { Route as DonorDonateConsentRouteImport } from './routes/donor.donate.consent'
import { Route as DonorDonateBatchRouteImport } from './routes/donor.donate.batch'
import { Route as NgoDonationsIdUnavailableRouteImport } from './routes/ngo.donations.$id.unavailable'
import { Route as NgoDonationsIdSuccessRouteImport } from './routes/ngo.donations.$id.success'
import { Route as NgoDonationsIdClaimRouteImport } from './routes/ngo.donations.$id.claim'
import { Route as NgoCollectionInstructionsIdRouteImport } from './routes/ngo.collection.instructions.$id'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityWalletRoute = CommunityWalletRouteImport.update({
  id: '/community-wallet',
  path: '/community-wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoVerificationRoute = NgoVerificationRouteImport.update({
  id: '/ngo/verification',
  path: '/ngo/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoProfileRoute = NgoProfileRouteImport.update({
  id: '/ngo/profile',
  path: '/ngo/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoNotVerifiedRoute = NgoNotVerifiedRouteImport.update({
  id: '/ngo/not-verified',
  path: '/ngo/not-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoExploreRoute = NgoExploreRouteImport.update({
  id: '/ngo/explore',
  path: '/ngo/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoDashboardRoute = NgoDashboardRouteImport.update({
  id: '/ngo/dashboard',
  path: '/ngo/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoClaimsRoute = NgoClaimsRouteImport.update({
  id: '/ngo/claims',
  path: '/ngo/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorProfileRoute = DonorProfileRouteImport.update({
  id: '/donor/profile',
  path: '/donor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorNetworkRoute = DonorNetworkRouteImport.update({
  id: '/donor/network',
  path: '/donor/network',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorImpactRoute = DonorImpactRouteImport.update({
  id: '/donor/impact',
  path: '/donor/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorHistoryRoute = DonorHistoryRouteImport.update({
  id: '/donor/history',
  path: '/donor/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorDashboardRoute = DonorDashboardRouteImport.update({
  id: '/donor/dashboard',
  path: '/donor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/admin/verification',
  path: '/admin/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoTrackIdRoute = NgoTrackIdRouteImport.update({
  id: '/ngo/track/$id',
  path: '/ngo/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoDonationsIdRoute = NgoDonationsIdRouteImport.update({
  id: '/ngo/donations/$id',
  path: '/ngo/donations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorDonateSuccessRoute = DonorDonateSuccessRouteImport.update({
  id: '/donor/donate/success',
  path: '/donor/donate/success',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorDonateReviewRoute = DonorDonateReviewRouteImport.update({
  id: '/donor/donate/review',
  path: '/donor/donate/review',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorDonateConsentRoute = DonorDonateConsentRouteImport.update({
  id: '/donor/donate/consent',
  path: '/donor/donate/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorDonateBatchRoute = DonorDonateBatchRouteImport.update({
  id: '/donor/donate/batch',
  path: '/donor/donate/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoDonationsIdUnavailableRoute =
  NgoDonationsIdUnavailableRouteImport.update({
    id: '/unavailable',
    path: '/unavailable',
    getParentRoute: () => NgoDonationsIdRoute,
  } as any)
const NgoDonationsIdSuccessRoute = NgoDonationsIdSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => NgoDonationsIdRoute,
} as any)
const NgoDonationsIdClaimRoute = NgoDonationsIdClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => NgoDonationsIdRoute,
} as any)
const NgoCollectionInstructionsIdRoute =
  NgoCollectionInstructionsIdRouteImport.update({
    id: '/ngo/collection/instructions/$id',
    path: '/ngo/collection/instructions/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community-wallet': typeof CommunityWalletRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/donor/dashboard': typeof DonorDashboardRoute
  '/donor/history': typeof DonorHistoryRoute
  '/donor/impact': typeof DonorImpactRoute
  '/donor/network': typeof DonorNetworkRoute
  '/donor/profile': typeof DonorProfileRoute
  '/ngo/claims': typeof NgoClaimsRoute
  '/ngo/dashboard': typeof NgoDashboardRoute
  '/ngo/explore': typeof NgoExploreRoute
  '/ngo/not-verified': typeof NgoNotVerifiedRoute
  '/ngo/profile': typeof NgoProfileRoute
  '/ngo/verification': typeof NgoVerificationRoute
  '/donor/donate/batch': typeof DonorDonateBatchRoute
  '/donor/donate/consent': typeof DonorDonateConsentRoute
  '/donor/donate/review': typeof DonorDonateReviewRoute
  '/donor/donate/success': typeof DonorDonateSuccessRoute
  '/ngo/donations/$id': typeof NgoDonationsIdRouteWithChildren
  '/ngo/track/$id': typeof NgoTrackIdRoute
  '/ngo/collection/instructions/$id': typeof NgoCollectionInstructionsIdRoute
  '/ngo/donations/$id/claim': typeof NgoDonationsIdClaimRoute
  '/ngo/donations/$id/success': typeof NgoDonationsIdSuccessRoute
  '/ngo/donations/$id/unavailable': typeof NgoDonationsIdUnavailableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community-wallet': typeof CommunityWalletRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/donor/dashboard': typeof DonorDashboardRoute
  '/donor/history': typeof DonorHistoryRoute
  '/donor/impact': typeof DonorImpactRoute
  '/donor/network': typeof DonorNetworkRoute
  '/donor/profile': typeof DonorProfileRoute
  '/ngo/claims': typeof NgoClaimsRoute
  '/ngo/dashboard': typeof NgoDashboardRoute
  '/ngo/explore': typeof NgoExploreRoute
  '/ngo/not-verified': typeof NgoNotVerifiedRoute
  '/ngo/profile': typeof NgoProfileRoute
  '/ngo/verification': typeof NgoVerificationRoute
  '/donor/donate/batch': typeof DonorDonateBatchRoute
  '/donor/donate/consent': typeof DonorDonateConsentRoute
  '/donor/donate/review': typeof DonorDonateReviewRoute
  '/donor/donate/success': typeof DonorDonateSuccessRoute
  '/ngo/donations/$id': typeof NgoDonationsIdRouteWithChildren
  '/ngo/track/$id': typeof NgoTrackIdRoute
  '/ngo/collection/instructions/$id': typeof NgoCollectionInstructionsIdRoute
  '/ngo/donations/$id/claim': typeof NgoDonationsIdClaimRoute
  '/ngo/donations/$id/success': typeof NgoDonationsIdSuccessRoute
  '/ngo/donations/$id/unavailable': typeof NgoDonationsIdUnavailableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community-wallet': typeof CommunityWalletRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/donor/dashboard': typeof DonorDashboardRoute
  '/donor/history': typeof DonorHistoryRoute
  '/donor/impact': typeof DonorImpactRoute
  '/donor/network': typeof DonorNetworkRoute
  '/donor/profile': typeof DonorProfileRoute
  '/ngo/claims': typeof NgoClaimsRoute
  '/ngo/dashboard': typeof NgoDashboardRoute
  '/ngo/explore': typeof NgoExploreRoute
  '/ngo/not-verified': typeof NgoNotVerifiedRoute
  '/ngo/profile': typeof NgoProfileRoute
  '/ngo/verification': typeof NgoVerificationRoute
  '/donor/donate/batch': typeof DonorDonateBatchRoute
  '/donor/donate/consent': typeof DonorDonateConsentRoute
  '/donor/donate/review': typeof DonorDonateReviewRoute
  '/donor/donate/success': typeof DonorDonateSuccessRoute
  '/ngo/donations/$id': typeof NgoDonationsIdRouteWithChildren
  '/ngo/track/$id': typeof NgoTrackIdRoute
  '/ngo/collection/instructions/$id': typeof NgoCollectionInstructionsIdRoute
  '/ngo/donations/$id/claim': typeof NgoDonationsIdClaimRoute
  '/ngo/donations/$id/success': typeof NgoDonationsIdSuccessRoute
  '/ngo/donations/$id/unavailable': typeof NgoDonationsIdUnavailableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community-wallet'
    | '/cookies'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/update-password'
    | '/admin/verification'
    | '/donor/dashboard'
    | '/donor/history'
    | '/donor/impact'
    | '/donor/network'
    | '/donor/profile'
    | '/ngo/claims'
    | '/ngo/dashboard'
    | '/ngo/explore'
    | '/ngo/not-verified'
    | '/ngo/profile'
    | '/ngo/verification'
    | '/donor/donate/batch'
    | '/donor/donate/consent'
    | '/donor/donate/review'
    | '/donor/donate/success'
    | '/ngo/donations/$id'
    | '/ngo/track/$id'
    | '/ngo/collection/instructions/$id'
    | '/ngo/donations/$id/claim'
    | '/ngo/donations/$id/success'
    | '/ngo/donations/$id/unavailable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community-wallet'
    | '/cookies'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/update-password'
    | '/admin/verification'
    | '/donor/dashboard'
    | '/donor/history'
    | '/donor/impact'
    | '/donor/network'
    | '/donor/profile'
    | '/ngo/claims'
    | '/ngo/dashboard'
    | '/ngo/explore'
    | '/ngo/not-verified'
    | '/ngo/profile'
    | '/ngo/verification'
    | '/donor/donate/batch'
    | '/donor/donate/consent'
    | '/donor/donate/review'
    | '/donor/donate/success'
    | '/ngo/donations/$id'
    | '/ngo/track/$id'
    | '/ngo/collection/instructions/$id'
    | '/ngo/donations/$id/claim'
    | '/ngo/donations/$id/success'
    | '/ngo/donations/$id/unavailable'
  id:
    | '__root__'
    | '/'
    | '/community-wallet'
    | '/cookies'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/update-password'
    | '/admin/verification'
    | '/donor/dashboard'
    | '/donor/history'
    | '/donor/impact'
    | '/donor/network'
    | '/donor/profile'
    | '/ngo/claims'
    | '/ngo/dashboard'
    | '/ngo/explore'
    | '/ngo/not-verified'
    | '/ngo/profile'
    | '/ngo/verification'
    | '/donor/donate/batch'
    | '/donor/donate/consent'
    | '/donor/donate/review'
    | '/donor/donate/success'
    | '/ngo/donations/$id'
    | '/ngo/track/$id'
    | '/ngo/collection/instructions/$id'
    | '/ngo/donations/$id/claim'
    | '/ngo/donations/$id/success'
    | '/ngo/donations/$id/unavailable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityWalletRoute: typeof CommunityWalletRoute
  CookiesRoute: typeof CookiesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  DonorDashboardRoute: typeof DonorDashboardRoute
  DonorHistoryRoute: typeof DonorHistoryRoute
  DonorImpactRoute: typeof DonorImpactRoute
  DonorNetworkRoute: typeof DonorNetworkRoute
  DonorProfileRoute: typeof DonorProfileRoute
  NgoClaimsRoute: typeof NgoClaimsRoute
  NgoDashboardRoute: typeof NgoDashboardRoute
  NgoExploreRoute: typeof NgoExploreRoute
  NgoNotVerifiedRoute: typeof NgoNotVerifiedRoute
  NgoProfileRoute: typeof NgoProfileRoute
  NgoVerificationRoute: typeof NgoVerificationRoute
  DonorDonateBatchRoute: typeof DonorDonateBatchRoute
  DonorDonateConsentRoute: typeof DonorDonateConsentRoute
  DonorDonateReviewRoute: typeof DonorDonateReviewRoute
  DonorDonateSuccessRoute: typeof DonorDonateSuccessRoute
  NgoDonationsIdRoute: typeof NgoDonationsIdRouteWithChildren
  NgoTrackIdRoute: typeof NgoTrackIdRoute
  NgoCollectionInstructionsIdRoute: typeof NgoCollectionInstructionsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-wallet': {
      id: '/community-wallet'
      path: '/community-wallet'
      fullPath: '/community-wallet'
      preLoaderRoute: typeof CommunityWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo/verification': {
      id: '/ngo/verification'
      path: '/ngo/verification'
      fullPath: '/ngo/verification'
      preLoaderRoute: typeof NgoVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo/profile': {
      id: '/ngo/profile'
      path: '/ngo/profile'
      fullPath: '/ngo/profile'
      preLoaderRoute: typeof NgoProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo/not-verified': {
      id: '/ngo/not-verified'
      path: '/ngo/not-verified'
      fullPath: '/ngo/not-verified'
      preLoaderRoute: typeof NgoNotVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo/explore': {
      id: '/ngo/explore'
      path: '/ngo/explore'
      fullPath: '/ngo/explore'
      preLoaderRoute: typeof NgoExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo/dashboard': {
      id: '/ngo/dashboard'
      path: '/ngo/dashboard'
      fullPath: '/ngo/dashboard'
      preLoaderRoute: typeof NgoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo/claims': {
      id: '/ngo/claims'
      path: '/ngo/claims'
      fullPath: '/ngo/claims'
      preLoaderRoute: typeof NgoClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor/profile': {
      id: '/donor/profile'
      path: '/donor/profile'
      fullPath: '/donor/profile'
      preLoaderRoute: typeof DonorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor/network': {
      id: '/donor/network'
      path: '/donor/network'
      fullPath: '/donor/network'
      preLoaderRoute: typeof DonorNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor/impact': {
      id: '/donor/impact'
      path: '/donor/impact'
      fullPath: '/donor/impact'
      preLoaderRoute: typeof DonorImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor/history': {
      id: '/donor/history'
      path: '/donor/history'
      fullPath: '/donor/history'
      preLoaderRoute: typeof DonorHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor/dashboard': {
      id: '/donor/dashboard'
      path: '/donor/dashboard'
      fullPath: '/donor/dashboard'
      preLoaderRoute: typeof DonorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/admin/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo/track/$id': {
      id: '/ngo/track/$id'
      path: '/ngo/track/$id'
      fullPath: '/ngo/track/$id'
      preLoaderRoute: typeof NgoTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo/donations/$id': {
      id: '/ngo/donations/$id'
      path: '/ngo/donations/$id'
      fullPath: '/ngo/donations/$id'
      preLoaderRoute: typeof NgoDonationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor/donate/success': {
      id: '/donor/donate/success'
      path: '/donor/donate/success'
      fullPath: '/donor/donate/success'
      preLoaderRoute: typeof DonorDonateSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor/donate/review': {
      id: '/donor/donate/review'
      path: '/donor/donate/review'
      fullPath: '/donor/donate/review'
      preLoaderRoute: typeof DonorDonateReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor/donate/consent': {
      id: '/donor/donate/consent'
      path: '/donor/donate/consent'
      fullPath: '/donor/donate/consent'
      preLoaderRoute: typeof DonorDonateConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor/donate/batch': {
      id: '/donor/donate/batch'
      path: '/donor/donate/batch'
      fullPath: '/donor/donate/batch'
      preLoaderRoute: typeof DonorDonateBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo/donations/$id/unavailable': {
      id: '/ngo/donations/$id/unavailable'
      path: '/unavailable'
      fullPath: '/ngo/donations/$id/unavailable'
      preLoaderRoute: typeof NgoDonationsIdUnavailableRouteImport
      parentRoute: typeof NgoDonationsIdRoute
    }
    '/ngo/donations/$id/success': {
      id: '/ngo/donations/$id/success'
      path: '/success'
      fullPath: '/ngo/donations/$id/success'
      preLoaderRoute: typeof NgoDonationsIdSuccessRouteImport
      parentRoute: typeof NgoDonationsIdRoute
    }
    '/ngo/donations/$id/claim': {
      id: '/ngo/donations/$id/claim'
      path: '/claim'
      fullPath: '/ngo/donations/$id/claim'
      preLoaderRoute: typeof NgoDonationsIdClaimRouteImport
      parentRoute: typeof NgoDonationsIdRoute
    }
    '/ngo/collection/instructions/$id': {
      id: '/ngo/collection/instructions/$id'
      path: '/ngo/collection/instructions/$id'
      fullPath: '/ngo/collection/instructions/$id'
      preLoaderRoute: typeof NgoCollectionInstructionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NgoDonationsIdRouteChildren {
  NgoDonationsIdClaimRoute: typeof NgoDonationsIdClaimRoute
  NgoDonationsIdSuccessRoute: typeof NgoDonationsIdSuccessRoute
  NgoDonationsIdUnavailableRoute: typeof NgoDonationsIdUnavailableRoute
}

const NgoDonationsIdRouteChildren: NgoDonationsIdRouteChildren = {
  NgoDonationsIdClaimRoute: NgoDonationsIdClaimRoute,
  NgoDonationsIdSuccessRoute: NgoDonationsIdSuccessRoute,
  NgoDonationsIdUnavailableRoute: NgoDonationsIdUnavailableRoute,
}

const NgoDonationsIdRouteWithChildren = NgoDonationsIdRoute._addFileChildren(
  NgoDonationsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityWalletRoute: CommunityWalletRoute,
  CookiesRoute: CookiesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  DonorDashboardRoute: DonorDashboardRoute,
  DonorHistoryRoute: DonorHistoryRoute,
  DonorImpactRoute: DonorImpactRoute,
  DonorNetworkRoute: DonorNetworkRoute,
  DonorProfileRoute: DonorProfileRoute,
  NgoClaimsRoute: NgoClaimsRoute,
  NgoDashboardRoute: NgoDashboardRoute,
  NgoExploreRoute: NgoExploreRoute,
  NgoNotVerifiedRoute: NgoNotVerifiedRoute,
  NgoProfileRoute: NgoProfileRoute,
  NgoVerificationRoute: NgoVerificationRoute,
  DonorDonateBatchRoute: DonorDonateBatchRoute,
  DonorDonateConsentRoute: DonorDonateConsentRoute,
  DonorDonateReviewRoute: DonorDonateReviewRoute,
  DonorDonateSuccessRoute: DonorDonateSuccessRoute,
  NgoDonationsIdRoute: NgoDonationsIdRouteWithChildren,
  NgoTrackIdRoute: NgoTrackIdRoute,
  NgoCollectionInstructionsIdRoute: NgoCollectionInstructionsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
